### ISSUE TITLE
 Header Nav 확인요함

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#40]
**Describe the bug**

현재 보여지는 페이지에서 다른페이지로 이동시 Head Nav도 Rerender가 되나 확인요함

**To Reproduce**
1. 메인페이지로 이동
2. 상단 Nav 중 하나 클릭
3. 페이지에서 Head 영역이 Rerendering여부 확인

**Expected behavior**
Head 부분은 Rerendering이 되지 않길 바람

**Desktop (please complete the following information):**

**Additional context**
확인후 댓글

**Comment by BKJang** [comment]
* `<NavLink>`로 구현된 부분이기 때문에 라우터를 통해 화면을 전환함.
* 추가적으로 Tab으로 구현하든지 방법은 찾아볼 예정.

**Comment by SeonHyungJo** [comment]
- origin/testing-navlink branch 확인요함
