### ISSUE TITLE
수정, 삭제, 등록 rest api 반환 정보

### ISSUE THREAD

**Issue by BKJang** [SeonHyungJo/YourHome#45]
**Describe the bug**
수정, 삭제, 등록 시 결과 코드 반환을 제대로 하고 있는지 확인 바람

**To Reproduce**
1. 수정, 삭제 버튼 클릭
2. rest api 반환 값으로 에러 코드 반환
3. 에러 코드에 따라 다른 에러 메세지 표시

**Expected behavior**
에러 코드 반환시 무조건 특별한 경우가 아니라면 Exception을 화면으로 던지면 안됨.
Exception을 catch 해서 error code를 result code로 반환해줘야 합니다.
해당 사항 확인하고 답변 바랍니다 :)

**Comment by SeonHyungJo** [comment]
Status Code 200으로 통일/ Fail 코드는 상황에 따라 다름 => 추후 정리 진행

**Comment by BKJang** [comment]
확인했습니다 :)
