### ISSUE TITLE
[품목관리] 클릭 이벤트 개선

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#48]
**Describe the bug**
왼쪽에 나오는 항목클릭상황

**Expected behavior**
화살표가 아닌 칸을 눌렀을때 이벤트가 발생하도록 개선

**Comment by eugene94** [comment]
YH- 48처리 완료했습니다

**Comment by SeonHyungJo** [comment]
확인했습니다
