### ISSUE TITLE
[품목관리] Nav 순서관리

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#52]
**Describe the bug**
아임홈 메뉴가 아래로 내려가는 현상

**To Reproduce**
1. 품목관리 클릭
2. 왼쪽 네비게이터 메뉴확인

**Expected behavior**
다른 항목은 순서가 보장이 되지 않더라도 아임홈 항목이 최상위로 오기를 바람

**Comment by eugene94** [comment]
해결했습니다. 특이사항으로는 로컬에서만 테스트 완료했으며 서버 re deploy시 다시 확인하겠습니다.

**Comment by SeonHyungJo** [comment]
확인했습니다. deploy 테스트 후 다시 Comment 적어주세요

**Comment by eugene94** [comment]
deploy 후 정상적용 확인되었습니다.

**Comment by SeonHyungJo** [comment]
확인했습니다
