### ISSUE TITLE
[품목관리] 아임홈 대메뉴 색상

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#53]
**Describe the bug**
현재 색상이 디자인색상과 같지 않음

**Expected behavior**
디자인과 색상을 맞추기를 원함 #616161 이색상 한번 확인바람

![psd](https://user-images.githubusercontent.com/24274424/50161349-ece76280-031e-11e9-97ff-47fe4847789b.jpg)

**Comment by eugene94** [comment]
클릭 시 div는 #363636으로 나오는데 #616161은 어디부분인가여

**Comment by eugene94** [comment]
수정했습니다.

**Comment by SeonHyungJo** [comment]
확인했습니다.
