### ISSUE TITLE
[품목관리] 세부메뉴 선택 개선

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#55]
**Describe the bug**
현재 수정버튼이 있을 경우 임으로 체크 버튼이 없어지고 row선택시 색상이 바뀌기를 바람

**Expected behavior**
row 선택시 기본색이 나와야함

**Comment by eugene94** [comment]
해결했습니다.

**Comment by SeonHyungJo** [comment]
완료했습니다
