### ISSUE TITLE
[품목관리] 기본 사이즈 문제

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#57]
![default](https://user-images.githubusercontent.com/24274424/50161827-29678e00-0320-11e9-8982-129bba41a6f7.jpg)
![default](https://user-images.githubusercontent.com/24274424/50161847-34222300-0320-11e9-8b1b-828f502a9981.jpg)

**Describe the bug**
품목내역이 나오는 영역이 크기가 min height가 꽉차야한다.

**To Reproduce**
1. 동원 F&B클릭
2. 왼쪽항목을 보게 되면 내역이 보이는 공간이 작음

**Expected behavior**
아래까지 꽉차야함 
자세한 모양은 디자인 사진 확인요함

**Comment by eugene94** [comment]
해결했습니다.

**Comment by SeonHyungJo** [comment]
확인했습니다
