### ISSUE TITLE
[품목관리] 상단 Food menu 고정문제

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#58]
**Describe the bug**
품목관리 상단 Food menu 고정되는 문제

**To Reproduce**
1. 아임홈 클릭
2. 아임홈 메뉴라고 나와야함
3. 동원 F&B클릭
4. 동원 F&B이 나와야함

**Expected behavior**
Nav메뉴에 맞는 제목이 나와야함

**Comment by eugene94** [comment]
해결했습니다.

**Comment by SeonHyungJo** [comment]
확인했습니다
