### ISSUE TITLE
**중요** 서버에 올린 front build파일에서 window.href 먹지않는 현상

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#65]
**Describe the bug**
초기 화면 접속시 token이 없어 login페이지로 redirect되지 않음

**Expected behavior**
초기접속시 리다이렉트가 잘되길 바람

react-router <Redirct> 태그 참조하면 좋을 듯

**Comment by BKJang** [comment]
YH-65 처리했습니다 :)

**Comment by SeonHyungJo** [comment]
추가수정 요청합니다
