### ISSUE TITLE
[미래지향] GraphQL을 적용한다면?

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#74]
[미래지향] GraphQL을 적용한다면?

현재에서 그래프큐엘을 적용한다면?
Cost는?
기간은?
이득은?

**Comment by BKJang** [comment]
GraphQL을 적용했을 때 장점은 새로운 정보가 필요할 때 마다 REST를 만들어야한다는 단점을 극복한 것이라고 생각합니다.

현재 REST 구조는 그대로 가고 HTTP Request가 불필요하게 많아지는 부분에서 GraphQL을 적용해보는건 어떨까요?
