### ISSUE TITLE
[품목관리] 아임홈에서 품목 추가시 버튼 고정

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#78]
**Describe the bug**
[품목관리] 아임홈에서 품목 추가시 버튼 고정

**To Reproduce**
1. 아임홈 클릭
2. 화면이 벗어나도록 품목추가
3. Scroll down to bottom
4. 품목추가, 품목삭제 버튼가 있음

**Expected behavior**
품목추가, 품목삭제버튼은 하위에 위치하면서 품목들만 스크롤되기를 바람

**Comment by eugene94** [comment]
해결했습니다.

**Comment by SeonHyungJo** [comment]
확인했습니다.
