### ISSUE TITLE
[품목관리] 다수의 수정을 누를경우 선택되는 현상

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#80]
**Describe the bug**
[품목관리] 다수의 수정을 누를경우 선택되는 현상

**To Reproduce**
1. 수정클릭
2. 수정 클릭된 상태에서 다른 품목 수정클릭
3. 이전에 수정클릭한 항목 선택된 상태가 됨

**Expected behavior**
이전에 수정을 누른 항목은 선택이 되지 않도록 수정

**Comment by eugene94** [comment]
66번 이슈 해결로 함께 해결완료

**Comment by SeonHyungJo** [comment]
확인했습니다.
