### ISSUE TITLE
[회원정보] 회원 상세 테이블 짝수 row마다 회색처리

### ISSUE THREAD

**Issue by SeonHyungJo** [SeonHyungJo/YourHome#81]
**Describe the bug**
[회원정보] 회원 상세 테이블 짝수 row마다 회색처리

**Expected behavior**
하단 링크에 사진대로 나오기를 바람

https://drive.google.com/open?id=1013r9tnfOTEu5Di2Fvggi93B2rsB9Ro6

**Comment by BKJang** [comment]
YH-81 처리했습니다 :)

**Comment by SeonHyungJo** [comment]
확인했습니다.
